### ISSUE TITLE
Eclipser does not support .launch file

### ISSUE THREAD

**Issue by bhatsarthak** [flurry/eclipser#5]
Can you please tell when eclipser will start supporting eclipse launch files. Also what is the current workarounds to convert launch files from eclipse to Intellij.

**Comment by rollinsio** [comment]
@bhatsarthak I suspect that this is not going to be updated here.  Feel free to fork it and maintain it.

**Comment by kukido** [comment]
@bhatsarthak the official repo is here: https://github.com/kukido/eclipser

@rollinsio can you remove the repo from under flurry? I asked Sean some time ago, but never got a response.

**Comment by rollinsio** [comment]
Thanks @kukido, I'll do so now.  Also, hope things are going well for you!

**Comment by kukido** [comment]
Things are going well, thank you very much! 👍
